#!/bin/sh

echo "" > "/tmp/kakoune-fzf-selection-$kak_client_pid"

# dont run rofi because my config for it is ugly with this kind of stuff ie just text
if [ -n "$TMUX" ]; then
    fzf-tmux -p 30%,30% --reverse --prompt $1 > "/tmp/kakoune-fzf-selection-$kak_client_pid" < "/tmp/fzf-input-$kak_client_pid"
else
    # echo
    echo "suspend-and-resume \"fzf --reverse > /tmp/kakoune-fzf-selection-%val{client_pid} < /tmp/fzf-input-%val{client_pid} \""
      > "$kak_command_fifo"
fi

